version: '3.7'

#  image with name fidemin/flaskapp:latest
services:
  flaskapp:
    image: fidemin/flaskapp:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
