"""empty message

Revision ID: 0302253ee6bc
Revises: 29f818b2ed2b
Create Date: 2024-04-15 21:40:14.564288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0302253ee6bc'
down_revision = '29f818b2ed2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('fk_employee_department_id_department', type_='foreignkey')
        batch_op.drop_constraint('fk_employee_is_head_of_department', type_='foreignkey')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key('fk_employee_is_head_of_department', 'department', ['is_head_of'], ['department_id'])
        batch_op.create_foreign_key('fk_employee_department_id_department', 'department', ['department_id'], ['department_id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
