"""empty message

Revision ID: 3a9aa3cd7cd2
Revises: 3629fb77d72a
Create Date: 2024-04-14 16:36:01.419186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9aa3cd7cd2'
down_revision = '3629fb77d72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_employee_department_id_department'), 'department', ['department_id'], ['department_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employee_department_id_department'), type_='foreignkey')

    # ### end Alembic commands ###
