"""empty message

Revision ID: a0fb9d41e293
Revises: 0302253ee6bc
Create Date: 2024-04-15 22:10:01.826587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fb9d41e293'
down_revision = '0302253ee6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('is_head_of')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_head_of', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
