apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flaskapp-as
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskapp
  targetCPUUtilizationPercentage: 50