apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: fidemin/flaskapp:0.2
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: flaskapp-secret
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: flaskapp-secret
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: flaskapp-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapp-secret
                  key: db_password