apiVersion: v1
kind: Pod
metadata:
  name: flaskapp
spec:
  containers:
    - name: flaskapp
      image: fidemin/flaskapp:latest
      ports:
        - containerPort: 3000
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_password
