apiVersion: v1
kind: Pod
metadata:
  name: flaskapp
spec:
  containers:
    - name: flaskapp
      image: fidemin/flaskapp:0.3
      ports:
        - containerPort: 8000
      resources:
        requests:
          cpu: "200m"
          memory: "500Mi"
        limits:
          cpu: "200m"
          memory: "500Mi"
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapp-secret
              key: db_password
        - name: LOGGING_CONFIG_FILE
          value: ./resources/logging_api.json

    - name: flaskapp-nginx
      image: fidemin/nginx:0.1
      ports:
        - containerPort: 80
