"""empty message

Revision ID: 40c7c0929e48
Revises: 0f3b2541c665
Create Date: 2024-05-18 21:11:21.525375

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '40c7c0929e48'
down_revision = '0f3b2541c665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = ENUM('M', 'F', name='gender_enum', create_type=False)
    gender_enum.create(op.get_bind(), checkfirst=False)
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('gender')

    ENUM(name='gender_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
